spin_manifest_version = 2

[application]
name = "tracing-spin"
version = "0.1.0"
authors = ["Caleb Schoepp <caleb.schoepp@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "tracing-spin"

[component.tracing-spin]
source = "../../../target/wasm32-wasi/release/exporter_tracing.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.tracing-spin.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
