[package]
name = "opentelemetry-wasi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opentelemetry = "0.22.0"
wit-bindgen = "0.24.0"

[workspace]
members = ["examples/*"]
