spin_manifest_version = 2

[application]
name = "with-tracing"
version = "0.1.0"
authors = ["Caleb Schoepp <caleb.schoepp@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "with-tracing"

[component.with-tracing]
source = "../../../target/wasm32-wasi/release/processor_tracing.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.with-tracing.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
