spin_manifest_version = 2

[application]
authors = ["Karthik Ganeshram <karthik.ganeshram@fermyon.com>"]
description = ""
name = "spin-basic-otel"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "spin-basic-otel"

[component.spin-basic-otel]
source = "dist/spin-basic-otel.wasm"
exclude_files = ["**/node_modules"]
[component.spin-basic-otel.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]