spin_manifest_version = 2

[application]
authors = ["Caleb Schoepp <caleb.schoepp@fermyon.com>"]
description = "A basic Spin application that directly consumes the opentelemetry-wasi crate"
name = "spin-basic"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "spin-basic"

[component.spin-basic]
source = "dist/spin-basic.wasm"
exclude_files = ["**/node_modules"]
[component.spin-basic.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]